version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    # command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yaml
      - ${PWD}/acme.json:/acme.json

  nginx:
    image: nginx:alpine
    labels:
      - traefik.http.routers.blog.rule=Host(`example.com`) && Path(`/blog`)
      - traefik.port=80
      - traefik.enable=true