global:
    checkNewVersion: true

api:
    insecure: true
    dashboard: true
    debug: true

providers:
    dockers:
        watch: true
        exposedByDefault: true
        useBindPortIP: true
        swarmMode: true
        swarmModeRefreshSeconds: 42